export default function HybridMath() {
  return <details className="smoker-model-details smoker-hybrid-math">
    <summary>Hybrid math & control algorithm</summary>
    <div>
      <p>Wood splits and pellets burn in dedicated fireboxes that feed one cooking chamber. Each firebox has its own intake, temperature and oxygen supply; both use the common exhaust. The fuel beds also keep separate mass, moisture, charcoal and temperature states. The engineering notes specify the coefficients, controller limits and tests.</p>
      <div className="smoker-equations">
        <section><h3>1. Conserve fuel and branch oxygen</h3><p className="smoker-formula">O₂ supplied to branch i = 0.232 × branch air mass flow</p><p className="smoker-formula">O₂ consumed by branch i ≤ O₂ supplied to branch i</p><p>Pyrolysis divides dry biomass into combustible gases and charcoal. Each bed burns within its own oxygen limit. Unused air in one firebox cannot burn fuel in the other, and gas that escapes releases no combustion heat.</p></section>
        <section><h3>2. Balance two fireboxes and one pit</h3><p className="smoker-formula">C<sub>fire,i</sub> × dT<sub>fire,i</sub>/dt = P<sub>burn,i</sub> − Q<sub>i→pit</sub> − Q<sub>fuel,i</sub> − Q<sub>loss,i</sub></p><p className="smoker-formula">Q<sub>into pit</sub> = Q<sub>wood→pit</sub> + Q<sub>pellet→pit</sub></p><p>Chemical heat release heats each firebox. Its transfer to the pit depends on the firebox-to-pit temperature difference. Fuel heating and water evaporation draw energy from the corresponding firebox. All P and Q terms are watts; C is joules per kelvin.</p></section>
        <section><h3>3. Allocate the pellet supplement</h3><p className="smoker-formula">P<sub>pellet target</sub> = max(0, P<sub>combustion demand</sub> − P<sub>wood forecast</sub>, P<sub>keep-warm floor</sub>)</p><p>With Automatic + Feed/dampers selected, the supervisor converts the common chamber heat demand into equivalent combustion power. It includes losses, temperature error, trend anticipation and stored heat in both fireboxes. It subtracts a forecast of wood chemical release and converts the residual to a wet pellet feed rate. In the normal wood-load range, a 0.10 kg/h keep-warm floor can exceed that residual to preserve the established pellet fire. This demand differs from actual heat transferred into the pit.</p></section>
        <section><h3>4. Respect actuator limits</h3><p className="smoker-formula">0 ≤ pellet feed ≤ 2.5 kg/h</p><p>Automatic control keeps a combustion-air floor for each intake. The common exhaust serves both branches. The controller freezes or limits integral action during lid openings and saturation. When a hot wood load exceeds available control authority, it commands pellet feed toward zero and reports the limit.</p></section>
      </div>
      <p>The wood estimate has ideal access to its simulated chemical heat release. For a physical smoker, the branch heat-transfer coefficients, burn kinetics, airflow curves, auger calibration and sensor delays need measured identification before these algorithms can be tuned for hardware.</p>
      <p>If pellet feed stays at zero long enough for its firebox to cool, automatic delivery pauses. The wood fire cannot relight the pellet bed; reset starts a fresh established-fire demonstration.</p>
      <p><a href="https://github.com/SydFloyd/kmproto-hub/blob/main/app/lab/smoker/HYBRID_MODEL.md" target="_blank" rel="noreferrer">Full equations, parameter tables, pseudocode and calibration plan</a> · <a href="https://github.com/SydFloyd/kmproto-hub/blob/main/app/lab/smoker/model.ts" target="_blank" rel="noreferrer">Executable model</a></p>
    </div>
  </details>;
}
